version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: healthline_postgres
    environment:
      POSTGRES_USER: healthline_user
      POSTGRES_PASSWORD: healthline_pass
      POSTGRES_DB: healthline_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthline_user -d healthline_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
