"""add_full_name_and_role_to_users

Revision ID: 610927b938bd
Revises: 713f0b0b362d
Create Date: 2025-10-04 13:57:23.944007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610927b938bd'
down_revision = '713f0b0b362d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
