"""add_child_name_to_conversations

Revision ID: 713f0b0b362d
Revises: b3c2bcb8ec15
Create Date: 2025-10-04 13:34:43.640417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713f0b0b362d'
down_revision = 'b3c2bcb8ec15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('child_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'child_name')
    # ### end Alembic commands ###
